export const state = {
  fileType: null,
  file: null,
  pdfDoc: null,
  curPage: 1,
  totalPages: 0,
  rawResponse: "",
  apiKey: "",
  groqApiKey: "",
  mistralApiKey: "",
  ollamaApiKey: "",
  openrouterApiKey: "",
  enabledProviders: {
    gemini: true,
    ollama: true,
    mistral: true,
    groq: true,
    openrouter: true
  },
  selectedModels: {
    gemini: ["gemini-3.1-pro-preview"],
    ollama: ["qwen3.5:cloud"],
    mistral: ["mistral-large-latest"],
    groq: ["meta-llama/llama-4-scout-17b-16e-instruct"],
    openrouter: ["google/gemma-4-26b-a4b-it:free"]
  },
  enableVisualization: false,
  visEngine: "matplotlib",
  visMode: "ask",
  visModelConfig: "ollama:qwen3.5:cloud",
  enableVisPlanner: false,
  visPlannerModelConfig: "ollama:qwen3.5:cloud",
  visEnabledModels: ["gemini:gemini-3.1-pro-preview", "ollama:qwen3.5:cloud"],
  activeTabId: "gemini:gemini-3.1-pro-preview",
  chatHistory: [],
  isSolved: false,
  pendingAttachment: null,
  isUserScrolledUp: false,
  answerCache: {},
  runningJobs: {},
  jobNodes: {},
};

export const sel = {
  active: false,
  x: 0,
  y: 0,
  w: 0,
  h: 0,
  mode: null,
  handle: null,
  startX: 0,
  startY: 0,
  origX: 0,
  origY: 0,
  origW: 0,
  origH: 0,
};
